# Generated by Django 4.2.7 on 2023-11-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='cnpj',
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='cpf',
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
    ]
