# Generated by Django 4.2.7 on 2023-11-22 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cadastro_cnpj_alter_cadastro_cpf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro',
            old_name='rua',
            new_name='endereco',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='numero',
        ),
    ]
