# Generated by Django 4.2.7 on 2023-11-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_rua_cadastro_endereco_remove_cadastro_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='cnpj',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='cpf',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
