# Generated by Django 4.2.7 on 2023-11-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cadastro_cnpj_alter_cadastro_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='id',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='Id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
