# Generated by Django 4.2.7 on 2023-11-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_cadastro_id_cadastro_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
